apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- deploy.yaml
- ingress.yaml
- rbac.yaml
- service.yaml

configMapGenerator:
- name: code-server-config
  env: code-server.properties

secretGenerator:
- name: code-ssh
  files:
  - ./ssh/id_rsa
  - ./ssh/id_rsa.pub

vars:
- name: CODESERVER_CONFIG_DOMAIN
  objref:
    kind: ConfigMap
    name: code-server-config
    apiVersion: v1
  fieldref:
    fieldpath: data.DOMAIN

namespace: code-server