apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-env-server
  namespace: code-server
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: dev-env-server
  namespace: code-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: dev-env-server
  namespace: code-server
